name: Hosting pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - "functions/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "functions/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment-hosting:
    name: Deploy Hosting
    concurrency:
      group: deployment-hosting
      cancel-in-progress: true
    # Run on main branch only
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      # TODO: Something with hosting build probably
      - name: Firebase deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TACO_PARROT }}"
          channelId: live
