name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build the project
      - name: Build Functions
        working-directory: ./functions
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: functions-lib
          path: ./functions/lib

  deployment:
    concurrency:
      group: deployment
      cancel-in-progress: true
    # Run on main branch only
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - uses: ./.github/actions/build.yml
        name: Build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Firebase deploy
        with:
          entrypoint: ./
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TACO_PARROT }}"
          channelId: live

