name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-functions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Functions
        working-directory: ./functions
        run: |
          npm install
          npm run lint
          npm run build

  deployment-functions:
    name: Deploy functions
    concurrency:
      group: deployment-functions
      cancel-in-progress: true
    # Run on main branch only
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-functions
    environment:
      name: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build Functions
        working-directory: ./functions
        run: |
          npm install
          npm run build
      - name: Firebase deploy functions
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --only functions --token ${{ secrets.FIREBASE_CI_TOKEN }}
      - name: Firebase deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TACO_PARROT }}"
          channelId: live

  deployment-hosting:
    name: Deploy Hosting
    concurrency:
      group: deployment-hosting
      cancel-in-progress: true
    # Run on main branch only
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    #needs: build-hosting
    environment:
      name: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      # TODO: Something with hosting build probably
      - name: Firebase deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TACO_PARROT }}"
          channelId: live
